apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  sessionAffinity: ClientIP  # 会话保持机制， 配置参数
  sessionAffinityConfig:     #  会话保持的最长时间
    clientIP:
      timeoutSeconds: 10800
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: webapp