apiVersion: v1
kind: Service         #表明是Kubernetes Service
metadata:
  name: mysql-service   #Service的全局唯一名称
#  namespace: <NAMESPACE-NAME>
  labels:
    app: mysql-service
spec:
  ports:
    - port: 3306          #Service提供服务的端口号
      targetPort: 3306
      name: mysql
  selector:               #Service对应的Pod拥有这里定义的标签, 确定了那些Pod副本(实例)对应本服务
    app: mysql
  type: ClusterIP