apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: '2022-06-28T09:39:09Z'
  generation: 1
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:podManagementPolicy': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:name': {}
            'f:spec':
              'f:containers':
                'k:{"name":"elasticsearch"}':
                  .: {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:lifecycle':
                    .: {}
                    'f:postStart':
                      .: {}
                      'f:exec':
                        .: {}
                        'f:command': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":9200,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                    'k:{"containerPort":9300,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/data"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/usr/share/elasticsearch/config/elasticsearch.yml"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                      'f:subPath': {}
                    'k:{"mountPath":"/usr/share/elasticsearch/plugins"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
              'f:dnsPolicy': {}
              'f:imagePullSecrets':
                .: {}
                'k:{"name":"mix-repo"}':
                  .: {}
                  'f:name': {}
              'f:initContainers':
                .: {}
                'k:{"name":"init-sysctl"}':
                  .: {}
                  'f:command': {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:resources': {}
                  'f:securityContext':
                    .: {}
                    'f:privileged': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes':
                .: {}
                'k:{"name":"es-conf"}':
                  .: {}
                  'f:configMap':
                    .: {}
                    'f:defaultMode': {}
                    'f:name': {}
                  'f:name': {}
                'k:{"name":"es-plugins"}':
                  .: {}
                  'f:hostPath':
                    .: {}
                    'f:path': {}
                    'f:type': {}
                  'f:name': {}
          'f:updateStrategy':
            'f:rollingUpdate':
              .: {}
              'f:partition': {}
            'f:type': {}
          'f:volumeClaimTemplates': {}
      manager: ACK-Console Apache-HttpClient
      operation: Update
      time: '2022-06-28T09:39:09Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:collisionCount': {}
          'f:currentReplicas': {}
          'f:currentRevision': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updateRevision': {}
          'f:updatedReplicas': {}
      manager: kube-controller-manager
      operation: Update
      time: '2022-07-11T03:27:36Z'
  name: elasticsearch
  namespace: kube-ops
  resourceVersion: '909147705'
  uid: ea5bc10a-3aea-4cbd-b7c3-d3d4a3128276
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: es7.16.2
  serviceName: ''
  template:
    metadata:
      labels:
        name: es7.16.2
    spec:
      containers:
        - image: 'registry.cn-hangzhou.aliyuncs.com/mixlink/elasticsearch:7.16.2'
          imagePullPolicy: IfNotPresent
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/bash
                  - '-c'
                  - >-
                    sysctl -w vm.max_map_count=262144; ulimit -l unlimited;chown
                    -R elasticsearch:elasticsearch /data;
          name: elasticsearch
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: es-data
            - mountPath: /usr/share/elasticsearch/plugins
              name: es-plugins
            - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              name: es-conf
              subPath: elasticsearch.yml
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: mix-repo
      initContainers:
        - command:
            - sysctl
            - '-w'
            - vm.max_map_count=655360
          image: 'busybox:stable'
          imagePullPolicy: IfNotPresent
          name: init-sysctl
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /home/software/elasticsearch/k8s-es/plugins
            type: ''
          name: es-plugins
        - configMap:
            defaultMode: 420
            name: es-config
          name: es-conf
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: es-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: alicloud-disk-ssd
        volumeMode: Filesystem
      status:
        phase: Pending
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: elasticsearch-84bd6447c
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: elasticsearch-84bd6447c
  updatedReplicas: 1
