apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
  namespace: chenzhou
data:
  elasticsearch.yml: |
    node.name: master
    cluster.initial_master_nodes: ["master"]
    node.master: true
    network.host: 0.0.0.0
    path.data: /data
    http.cors.enabled: true
    http.cors.allow-origin: "*"
