apiVersion: apps/v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
    - name: tomcat
      image: tomcat
      ports:
        - containerPort: 8080
      volumeMounts:           #Volume 挂载到tomcat容器目录下
      - name: app-logs
        mountPath: /usr/local/tomcat/logs
    - name: busybox
      image: busybox
      command: [ "sh", "-c", "tail -f /logs/catalina*.log"]
      volumeMounts:        #Volume 同时挂载到logreader容器目录下
      - name: app-logs
        mountPath: /logs
  volumes:                #Volume
    - name: app-logs      #Volume名称
      emptyDir: {}        #类型
