apiVersion: v1
kind: ReplicationControler
metadata:
  name: redis-master
  labels:
    name: redis-master
spec:
  replicas: 1
  selector:
    name: redis-master
    template:
      metadata:
        labels:
          app: redis-master
      spec:
        containers:
          - name: master
            image: kubeguide/redis-master
            ports:
              - containerPort: 6379
        nodeSelector:
          zone: north