apiVersion: v1
kind: Pod
metadata:
  name: static-web
  lables:
    name: static-web
spec:
  containers:
    - name: static-web
      image: nginx
      ports:
        - name: web
          containerPort: 80