apiVersion: v1
kind: Pod
metadata:
  name: pod-with-healthcheck
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:    # LivenessProbe健康检查
        httpGet:
          path: /_status/healthz
          port: 80
        initialDelaySeconds: 30
        timeoutSeconds: 1