apiVersion: scheduling.k8s.io/v1betal
kind: PriorityClass
metadata:
  name: high-priority
value: 100000
globalDefault: false
description: "The priority class should be used for XYZ service pods only."