apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer  # LoadBalancer类型
  selector:
    app: MyApp
  ports:
    - portocol: TCP
      port: 80
      targetPort: 9376
  clusterIP: 10.0.171.239

 #在服务创建成功之后，云服务商会再Service定义中补充LoadBalancer的IP地址（status字段）：
 status:
  loadBalancer:
    ingress:
      - ip: 192.0.2.127

