apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataease
  namespace: chenzhou
  labels:
    app: dataease
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataease
  template:
    metadata:
      labels:
        app: dataease
    spec:
      containers:
        - name: dataease
          image: 'registry.cn-hangzhou.aliyuncs.com/qoct/dataease:v2'
          ports:
            - containerPort: 8081
          securityContext:
            privileged: true
          volumeMounts:
            - name: volume-dataease-data
              mountPath: /opt/dataease/data
      volumes:
        - name: volume-dataease-data
          persistentVolumeClaim:
            claimName: dataease-data
      imagePullSecrets:
        - name: myregistrykey

---
apiVersion: v1
kind: Service
metadata:
  name: dataease-service
  namespace: chenzhou
  labels:
    app: dataease-service
spec:
  ports:
    - port: 80
      targetPort: 8081
      name: dataease
  selector:
    app: dataease
  type: ClusterIP